CREATE TABLE personel (_id int NOT NULL, ad varchar(30) NOT NULL DEFAULT '', soyad varchar(30) NOT NULL DEFAULT '', birim varchar(30) NOT NULL DEFAULT '', ucret int NOT NULL DEFAULT 2943)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2001, 'Ali','Yılmaz','Muhasebe',5000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2002, 'Ayşe','Yıldız','Ar-Ge',6000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2003, 'Fatma','Demir','İnsan Kaynakları',5000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2004, 'Veli','Coşkun','Sistem Yönetimi',6000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2005, 'Gül','Toprak','Ar-Ge',8000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2006, 'Emine','Şen','Ar-Ge',10000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2007, 'Osman','Kaya','Ar-Ge',12000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2008, 'Hüseyin','Çelik','Proje Yönetimi',9000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2009, 'Ali','Yıldırım','Ar-Ge',7000)
INSERT INTO personel (_id, ad, soyad, birim, ucret) VALUES (2010, 'Aydın','Aslan','Proje Yönetimi',11000)
